[build]
command = """
curl -sSL https://install.python-poetry.org | python3 -
pip install --upgrade pip
pip install -r requirements.txt
"""
publish = "templates"

[dev]
framework = "#custom"
command = "python app.py"

[[redirects]]
from = "/*"
to = "/.netlify/functions/app"
status = 200

[functions]
directory = "netlify/functions"
node_bundler = "esbuild"

[build.environment]
PYTHON_VERSION = "3.9"
POETRY_VERSION = "1.4.2"
PIP_VERSION = "23.1.2" 