[build]
command = "pip install -r requirements.txt"
publish = "templates"

[dev]
framework = "#custom"
command = "python app.py"

[[redirects]]
from = "/*"
to = "/.netlify/functions/app"
status = 200

[functions]
directory = "netlify/functions"
node_bundler = "esbuild"

[build.environment]
PYTHON_VERSION = "3.9" 