[build]
command = "pip install -r requirements.txt"
publish = "templates"
functions = "netlify/functions"

[build.environment]
PYTHON_VERSION = "3.8"

[[redirects]]
from = "/*"
to = "/.netlify/functions/app"
status = 200

[functions]
directory = "netlify/functions" 